package az.etaskify.util.enums;

public enum NotificationType {
    TASK_ASSIGNED, INVITE_RECEIVED, JOIN_ACCEPTED, INVITE_REJECTED, JOIN_REQUEST_RECEIVED, JOIN_REQUEST_APPROVED, JOIN_REQUEST_REJECTED
}
